---
apiVersion: v1
kind: Template
labels:
  app: "${APP_NAME}-${JOB_NAME}"
  template: "${APP_NAME}-${JOB_NAME}-caddy-bc-template"
metadata:
  name: "${APP_NAME}-${JOB_NAME}-caddy-dc"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: "${APP_NAME}-${JOB_NAME}-caddy"
  spec:
    ports:
    - name: 2015-tcp
      port: 2015
      protocol: TCP
      targetPort: 2015
    selector:
      app: "${APP_NAME}-${JOB_NAME}"
      deploymentconfig: "${APP_NAME}-${JOB_NAME}-caddy"
      role: caddy
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: "${APP_NAME}-${JOB_NAME}-caddy"
  spec:
    host: "${HOST_ROUTE}"
    path: "${PATH_ROOT}"
    port:
      targetPort: 2015-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: "${APP_NAME}-${JOB_NAME}-caddy"
      weight: 100
    wildcardPolicy: None
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: "${APP_NAME}-${JOB_NAME}-caddy"
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: "${APP_NAME}-${JOB_NAME}"
      deploymentconfig: "${APP_NAME}-${JOB_NAME}-caddy"
      role: caddy
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: "${APP_NAME}-${JOB_NAME}"
          deploymentconfig: "${APP_NAME}-${JOB_NAME}-caddy"
          role: caddy
      spec:
        containers:
        - env:
          - name: PATH_ROOT
            value: "${PATH_ROOT}"
          - name: CADDY_SERVICE_PORT
            value: "2015"
          - name: CADDY_REDIRECT_URI
            value: "${CADDY_REDIRECT_URI}"
          image: "docker-registry.default.svc:5000/${NAMESPACE}/${REPO_NAME}-caddy:${JOB_NAME}"
          imagePullPolicy: Always
          name: "${APP_NAME}-${JOB_NAME}-caddy"
          ports:
          - containerPort: 2015
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "${PATH_ROOT}"
              port: 2015
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            requests:
              cpu: "${CPU_REQUEST}"
              memory: "${MEMORY_REQUEST}"
            limits:
              cpu: "${CPU_LIMIT}"
              memory: "${MEMORY_LIMIT}"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
parameters:
- name: REPO_NAME
  description: Application repository name
  required: true
- name: JOB_NAME
  description: Job identifier (i.e. 'pr-5' OR 'master')
  required: true
- name: NAMESPACE
  description: Target namespace reference (i.e. 'k8vopl-dev')
  required: true
- name: APP_NAME
  description: Application name
  required: true
- name: CPU_REQUEST
  description: Requested CPU per pod (in millicores ex. 500m)
  required: true
  value: 100m
- name: MEMORY_REQUEST
  description: Requested Memory per pod (in gigabytes Gi or megabytes Mi ex. 500Mi)
  required: true
  value: 256Mi
- name: CPU_LIMIT
  description: Limit Peak CPU per pod (in millicores ex. 1000m)
  required: true
  value: 500m
- name: MEMORY_LIMIT
  description: Limit Peak Memory per pod (in gigabytes Gi or megabytes Mi ex. 2Gi)
  required: true
  value: 1Gi
- name: HOST_ROUTE
  description: The host the route will use to expose service outside cluster
  required: true
- name: PATH_ROOT
  description: Root of path where application is hosted (ex. '/pr-5' or '/getok')
  required: true
  value: "/"
- name: CADDY_REDIRECT_URI
  description: Redirect to url
  required: true
  value: "https://getok.pathfinder.gov.bc.ca/getok"
